const ALL_LANGUAGES = {
  af: { name: "Afrikaans", script: "Latin" },
  am: { name: "Amharic", script: "Ethiopic" },
  ar: { name: "Arabic", script: "Arabic" },
  bg: { name: "Bulgarian", script: "Cyrillic" },
  "bg-Latn": { name: "Bulgarian", script: "Latin" },
  bn: { name: "Bangla", script: "Bangla" },
  bs: { name: "Bosnian", script: "Latin" },
  ca: { name: "Catalan", script: "Latin" },
  ceb: { name: "Cebuano", script: "Latin" },
  co: { name: "Corsican", script: "Latin" },
  cs: { name: "Czech", script: "Latin" },
  cy: { name: "Welsh", script: "Latin" },
  da: { name: "Danish", script: "Latin" },
  de: { name: "German", script: "Latin" },
  el: { name: "Greek", script: "Greek" },
  "el-Latn": { name: "Greek", script: "Latin" },
  en: { name: "English", script: "Latin" },
  eo: { name: "Esperanto", script: "Latin" },
  es: { name: "Spanish", script: "Latin" },
  et: { name: "Estonian", script: "Latin" },
  eu: { name: "Basque", script: "Latin" },
  fa: { name: "Persian", script: "Arabic" },
  fi: { name: "Finnish", script: "Latin" },
  fil: { name: "Filipino", script: "Latin" },
  fr: { name: "French", script: "Latin" },
  fy: { name: "Western Frisian", script: "Latin" },
  ga: { name: "Irish", script: "Latin" },
  gd: { name: "Scottish Gaelic", script: "Latin" },
  gl: { name: "Galician", script: "Latin" },
  gu: { name: "Gujarati", script: "Gujarati" },
  ha: { name: "Hausa", script: "Latin" },
  haw: { name: "Hawaiian", script: "Latin" },
  hi: { name: "Hindi", script: "Devanagari" },
  "hi-Latn": { name: "Hindi", script: "Latin" },
  hmn: { name: "Hmong", script: "Latin" },
  hr: { name: "Croatian", script: "Latin" },
  ht: { name: "Haitian Creole", script: "Latin" },
  hu: { name: "Hungarian", script: "Latin" },
  hy: { name: "Armenian", script: "Armenian" },
  id: { name: "Indonesian", script: "Latin" },
  ig: { name: "Igbo", script: "Latin" },
  is: { name: "Icelandic", script: "Latin" },
  it: { name: "Italian", script: "Latin" },
  iw: { name: "Hebrew", script: "Hebrew" },
  ja: { name: "Japanese", script: "Japanese" },
  "ja-Latn": { name: "Japanese", script: "Latin" },
  jv: { name: "Javanese", script: "Latin" },
  ka: { name: "Georgian", script: "Georgian" },
  kk: { name: "Kazakh", script: "Cyrillic" },
  km: { name: "Khmer", script: "Khmer" },
  kn: { name: "Kannada", script: "Kannada" },
  ko: { name: "Korean", script: "Korean" },
  ku: { name: "Kurdish", script: "Latin" },
  ky: { name: "Kyrgyz", script: "Cyrillic" },
  la: { name: "Latin", script: "Latin" },
  lb: { name: "Luxembourgish", script: "Latin" },
  lo: { name: "Lao", script: "Lao" },
  lt: { name: "Lithuanian", script: "Latin" },
  lv: { name: "Latvian", script: "Latin" },
  mg: { name: "Malagasy", script: "Latin" },
  mi: { name: "Maori", script: "Latin" },
  mk: { name: "Macedonian", script: "Cyrillic" },
  ml: { name: "Malayalam", script: "Malayalam" },
  mn: { name: "Mongolian", script: "Cyrillic" },
  mr: { name: "Marathi", script: "Devanagari" },
  ms: { name: "Malay", script: "Latin" },
  mt: { name: "Maltese", script: "Latin" },
  my: { name: "Burmese", script: "Myanmar" },
  ne: { name: "Nepali", script: "Devanagari" },
  nl: { name: "Dutch", script: "Latin" },
  no: { name: "Norwegian", script: "Latin" },
  ny: { name: "Nyanja", script: "Latin" },
  pa: { name: "Punjabi", script: "Gurmukhi" },
  pl: { name: "Polish", script: "Latin" },
  ps: { name: "Pashto", script: "Arabic" },
  pt: { name: "Portuguese", script: "Latin" },
  ro: { name: "Romanian", script: "Latin" },
  ru: { name: "Russian", script: "Cyrillic" },
  "ru-Latn": { name: "Russian", script: "English" },
  sd: { name: "Sindhi", script: "Arabic" },
  si: { name: "Sinhala", script: "Sinhala" },
  sk: { name: "Slovak", script: "Latin" },
  sl: { name: "Slovenian", script: "Latin" },
  sm: { name: "Samoan", script: "Latin" },
  sn: { name: "Shona", script: "Latin" },
  so: { name: "Somali", script: "Latin" },
  sq: { name: "Albanian", script: "Latin" },
  sr: { name: "Serbian", script: "Cyrillic" },
  st: { name: "Southern Sotho", script: "Latin" },
  su: { name: "Sundanese", script: "Latin" },
  sv: { name: "Swedish", script: "Latin" },
  sw: { name: "Swahili", script: "Latin" },
  ta: { name: "Tamil", script: "Tamil" },
  te: { name: "Telugu", script: "Telugu" },
  tg: { name: "Tajik", script: "Cyrillic" },
  th: { name: "Thai", script: "Thai" },
  tr: { name: "Turkish", script: "Latin" },
  uk: { name: "Ukrainian", script: "Cyrillic" },
  ur: { name: "Urdu", script: "Arabic" },
  uz: { name: "Uzbek", script: "Latin" },
  vi: { name: "Vietnamese", script: "Latin" },
  xh: { name: "Xhosa", script: "Latin" },
  yi: { name: "Yiddish", script: "Hebrew" },
  yo: { name: "Yoruba", script: "Latin" },
  zh: { name: "Chinese", script: "Han (including Simplified and Traditional)" },
  "zh-Latn": { name: "Chinese", script: "Latin" },
  zu: { name: "Zulu", script: "Latin" }
};

// Default enabled languages
const DEFAULT_LANGUAGES = {
  ja: "Japanese",
  zh: "Chinese", 
  ko: "Korean",
  ar: "Arabic",
  ru: "Russian",
  th: "Thai"
};