// Inspirational quotes for ad replacement
const QUOTES = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It is during our darkest moments that we must focus to see the light. - Aristotle",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Life is either a daring adventure or nothing at all. - Helen Keller",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "The only impossible thing is that which you don't attempt. - Spanish Proverb",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Everything you've ever wanted is on the other side of fear. - George Addair",
  "Dream big and dare to fail. - Norman Vaughan",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Too many of us are not living our dreams because we are living our fears. - Les Brown",
  "I didn't fail the test. I just found 100 ways to do it wrong. - Benjamin Franklin",
  "A person who never made a mistake never tried anything new. - Albert Einstein",
  "The person who says it cannot be done should not interrupt the person who is doing it. - Chinese Proverb",
  "There are no traffic jams along the extra mile. - Roger Staubach",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
  "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
  "When everything seems to be going against you, remember that the airplane takes off against the wind. - Henry Ford",
  "The mind is everything. What you think you become. - Buddha",
  "The best revenge is massive success. - Frank Sinatra",
  "Life is 10% what happens to you and 90% how you react to it. - Charles R. Swindoll",
  "Fall seven times and stand up eight. - Japanese Proverb",
  "Twenty years from now you will be more disappointed by the things that you didn't do. - Mark Twain",
  "The difference between ordinary and extraordinary is that little extra. - Jimmy Johnson",
  "Do what you can, where you are, with what you have. - Theodore Roosevelt",
  "Everything has beauty, but not everyone can see. - Confucius",
  "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
  "The only way to have a friend is to be one. - Ralph Waldo Emerson",
  
  // Success & Achievement
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
  "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
  
  // Wisdom & Knowledge
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "Knowledge speaks, but wisdom listens. - Jimi Hendrix",
  "The fool doth think he is wise, but the wise man knows himself to be a fool. - William Shakespeare",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. - Rumi",
  "The only source of knowledge is experience. - Albert Einstein",
  "Real knowledge is to know the extent of one's ignorance. - Confucius",
  "Knowing yourself is the beginning of all wisdom. - Aristotle",
  "The more I learn, the more I realize how much I don't know. - Albert Einstein",
  "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. - Albert Einstein",
  
  // Motivation & Perseverance
  "The harder you work for something, the greater you'll feel when you achieve it. - Anonymous",
  "Don't limit your challenges. Challenge your limits. - Anonymous",
  "Push yourself, because no one else is going to do it for you. - Anonymous",
  "Great things never come from comfort zones. - Anonymous",
  "Wake up with determination. Go to bed with satisfaction. - Anonymous",
  "Do something today that your future self will thank you for. - Sean Patrick Flanery",
  "Little things make big days. - Anonymous",
  "It's going to be hard, but hard does not mean impossible. - Anonymous",
  "Don't quit. Suffer now and live the rest of your life as a champion. - Muhammad Ali",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  
  // Leadership & Character
  "A leader is one who knows the way, goes the way, and shows the way. - John C. Maxwell",
  "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things. - Ronald Reagan",
  "Leadership is not about being in charge. It's about taking care of those in your charge. - Simon Sinek",
  "Character is how you treat those who can do nothing for you. - Anonymous",
  "Be yourself; everyone else is already taken. - Oscar Wilde",
  "Integrity is doing the right thing, even when no one is watching. - C.S. Lewis",
  "The true test of a man's character is what he does when no one is watching. - John Wooden",
  "Leadership is the capacity to translate vision into reality. - Warren Bennis",
  "Management is doing things right; leadership is doing the right things. - Peter Drucker",
  "A genuine leader is not a searcher for consensus but a molder of consensus. - Martin Luther King Jr.",
  
  // Creativity & Innovation
  "Creativity is intelligence having fun. - Albert Einstein",
  "The secret to creativity is knowing how to hide your sources. - Einstein",
  "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
  "The worst enemy to creativity is self-doubt. - Sylvia Plath",
  "Creativity takes courage. - Henri Matisse",
  "The creative adult is the child who survived. - Ursula K. Le Guin",
  "Originality is nothing but judicious imitation. - Voltaire",
  "You can't wait for inspiration. You have to go after it with a club. - Jack London",
  "The way to get good ideas is to get lots of ideas and throw the bad ones away. - Linus Pauling",
  "Creativity is the power to connect the seemingly unconnected. - William Plomer",
  
  // Change & Growth
  "Be the change you wish to see in the world. - Mahatma Gandhi",
  "Change is the only constant in life. - Heraclitus",
  "The only way to make sense out of change is to plunge into it, move with it, and join the dance. - Alan Watts",
  "Progress is impossible without change, and those who cannot change their minds cannot change anything. - George Bernard Shaw",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "Everyone thinks of changing the world, but no one thinks of changing himself. - Leo Tolstoy",
  "Growth begins when we begin to accept our own weakness. - Jean Vanier",
  "The bamboo that bends is stronger than the oak that resists. - Japanese Proverb",
  "What got you here won't get you there. - Marshall Goldsmith",
  "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
  
  // Courage & Bravery
  "Courage is not the absence of fear, but the triumph over it. - Nelson Mandela",
  "It takes courage to grow up and become who you really are. - E.E. Cummings",
  "Courage is grace under pressure. - Ernest Hemingway",
  "The brave man is not he who does not feel afraid, but he who conquers that fear. - Nelson Mandela",
  "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.' - Mary Anne Radmacher",
  "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. - Eleanor Roosevelt",
  "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently. - Maya Angelou",
  "It is not the critic who counts; not the man who points out how the strong man stumbles. - Theodore Roosevelt",
  "Fortune favors the brave. - Latin Proverb",
  "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. - Lao Tzu",
  
  // Happiness & Joy
  "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Happiness is when what you think, what you say, and what you do are in harmony. - Mahatma Gandhi",
  "The most important thing is to enjoy your life—to be happy—it's all that matters. - Audrey Hepburn",
  "Happiness is a warm puppy. - Charles M. Schulz",
  "For every minute you are angry you lose sixty seconds of happiness. - Ralph Waldo Emerson",
  "Happiness is not a goal; it is a by-product. - Eleanor Roosevelt",
  "The secret of happiness is not in doing what one likes, but in liking what one does. - James M. Barrie",
  "Count your age by friends, not years. Count your life by smiles, not tears. - John Lennon",
  "Happiness depends upon ourselves. - Aristotle",
  
  // Time & Life
  "Time you enjoy wasting is not wasted time. - Marthe Troly-Curtin",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. - Bill Keane",
  "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
  "Time flies over us, but leaves its shadow behind. - Nathaniel Hawthorne",
  "Lost time is never found again. - Benjamin Franklin",
  "Time is what we want most, but what we use worst. - William Penn",
  "The bad news is time flies. The good news is you're the pilot. - Michael Altshuler",
  "Don't count the days, make the days count. - Muhammad Ali",
  "Time is the most valuable thing a man can spend. - Theophrastus",
  "How we spend our days is, of course, how we spend our lives. - Annie Dillard",
  
  // Dreams & Aspirations
  "All our dreams can come true, if we have the courage to pursue them. - Walt Disney",
  "A dream doesn't become reality through magic; it takes sweat, determination and hard work. - Colin Powell",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "Dreams are illustrations from the book your soul is writing about you. - Marsha Norman",
  "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly. - Langston Hughes",
  "A dream you dream alone is only a dream. A dream you dream together is reality. - John Lennon",
  "Dreams don't work unless you do. - John C. Maxwell",
  "The only thing worse than starting something and failing... is not starting something. - Seth Godin",
  "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
  "Every great dream begins with a dreamer. - Harriet Tubman",
  
  // Learning & Education
  "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "Learning never exhausts the mind. - Leonardo da Vinci",
  "The beautiful thing about learning is that nobody can take it away from you. - B.B. King",
  "Anyone who stops learning is old, whether at twenty or eighty. - Henry Ford",
  "The expert in anything was once a beginner. - Helen Hayes",
  "Education is not the filling of a pail, but the lighting of a fire. - William Butler Yeats",
  "I am always ready to learn although I do not always like being taught. - Winston Churchill",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. - Brian Herbert",
  
  // Humor & Wit
  "I'm not superstitious, but I am a little stitious. - Michael Scott",
  "The road to success is dotted with many tempting parking spaces. - Will Rogers",
  "People say nothing is impossible, but I do nothing every day. - A.A. Milne",
  "Better to remain silent and be thought a fool than to speak out and remove all doubt. - Abraham Lincoln",
  "If you think you are too small to make a difference, try sleeping with a mosquito. - Dalai Lama",
  "The elevator to success is out of order. You'll have to use the stairs, one step at a time. - Joe Girard",
  "I am so clever that sometimes I don't understand a single word of what I am saying. - Oscar Wilde",
  "People often say that motivation doesn't last. Well, neither does bathing—that's why we recommend it daily. - Zig Ziglar",
  "Life is like a sewer... what you get out of it depends on what you put into it. - Tom Lehrer",
  "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
  
  // Relationships & Love
  "The greatest gift of life is friendship, and I have received it. - Hubert H. Humphrey",
  "A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
  "Love is composed of a single soul inhabiting two bodies. - Aristotle",
  "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart. - Helen Keller",
  "We accept the love we think we deserve. - Stephen Chbosky",
  "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. - Lao Tzu",
  "To love and be loved is to feel the sun from both sides. - David Viscott",
  "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed. - Carl Jung",
  "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.' - C.S. Lewis",
  "The only way to have a friend is to be one. - Ralph Waldo Emerson",
  
  // Action & Initiative
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Action is the foundational key to all success. - Pablo Picasso",
  "The path to success is to take massive, determined action. - Tony Robbins",
  "An idea not coupled with action will never get any bigger than the brain cell it occupied. - Arnold Glasow",
  "Well done is better than well said. - Benjamin Franklin",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Do you want to know who you are? Don't ask. Act! Action will delineate and define you. - Thomas Jefferson",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. - Leonardo da Vinci",
  "In any moment of decision, the best thing you can do is the right thing. The worst thing you can do is nothing. - Theodore Roosevelt",
  
  // Mindset & Attitude
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "A positive attitude causes a chain reaction of positive thoughts, events and outcomes. - Wade Boggs",
  "Attitude is a little thing that makes a big difference. - Winston Churchill",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. - Winston Churchill",
  "Once you replace negative thoughts with positive ones, you'll start having positive results. - Willie Nelson",
  "Positive anything is better than negative nothing. - Elbert Hubbard",
  "Your attitude, not your aptitude, will determine your altitude. - Zig Ziglar",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only disability in life is a bad attitude. - Scott Hamilton",
  
  // Purpose & Meaning
  "The meaning of life is to find your gift. The purpose of life is to give it away. - Pablo Picasso",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate. - Ralph Waldo Emerson",
  "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
  "You were born with wings, why prefer to crawl through life? - Rumi",
  "The purpose of life is to live it, to taste experience to the utmost. - Eleanor Roosevelt",
  "Life is never made unbearable by circumstances, but only by lack of meaning and purpose. - Viktor Frankl",
  "Your purpose in life is to find your purpose and give your whole heart and soul to it. - Buddha",
  "The meaning of life is to give life meaning. - Ken Hudgins",
  "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
  "The purpose of our lives is to add value to the people of this generation and those that follow. - R. Buckminster Fuller",
  
  // Self-Improvement
  "Be yourself; everyone else is already taken. - Oscar Wilde",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "There is only one corner of the universe you can be certain of improving, and that's your own self. - Aldous Huxley",
  "The only person you should try to be better than is the person you were yesterday. - Anonymous",
  "Work on yourself more than you do on your job. - Jim Rohn",
  "Make the most of yourself by fanning the tiny, inner sparks of possibility into flames of achievement. - Golda Meir",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "Self-care is not selfish. You cannot serve from an empty vessel. - Eleanor Brown",
  "The curious paradox is that when I accept myself just as I am, then I can change. - Carl Rogers",
  
  // Resilience & Strength
  "The oak fought the wind and was broken, the willow bent when it must and survived. - Robert Jordan",
  "Rock bottom became the solid foundation on which I rebuilt my life. - J.K. Rowling",
  "The human capacity for burden is like bamboo—far more flexible than you'd ever believe at first glance. - Jodi Picoult",
  "You may have to fight a battle more than once to win it. - Margaret Thatcher",
  "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't. - Rikki Rogers",
  "The strongest people are not those who show strength in front of us, but those who win battles we know nothing about. - Anonymous",
  "Tough times never last, but tough people do. - Robert H. Schuller",
  "When we long for life without difficulties, remind us that oaks grow strong in contrary winds. - Peter Marshall",
  "A smooth sea never made a skilled sailor. - Franklin D. Roosevelt",
  "Stars can't shine without darkness. - Anonymous",
  
  // Focus & Discipline
  "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
  "You will never change your life until you change something you do daily. - Mike Murdock",
  "Focus on being productive instead of busy. - Tim Ferriss",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days. - Zig Ziglar",
  "Where focus goes, energy flows. - Tony Robbins",
  "The secret of change is to focus all of your energy not on fighting the old, but on building the new. - Socrates",
  "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus. - Alexander Graham Bell",
  "You can do anything, but not everything. - David Allen",
  "The key is not to prioritize what's on your schedule, but to schedule your priorities. - Stephen Covey",
  
  // Gratitude & Appreciation
  "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow. - Melody Beattie",
  "Gratitude is not only the greatest of virtues, but the parent of all others. - Marcus Tullius Cicero",
  "When we give cheerfully and accept gratefully, everyone is blessed. - Maya Angelou",
  "Gratitude is the healthiest of all human emotions. - Zig Ziglar",
  "The way to develop the best that is in a person is by appreciation and encouragement. - Charles Schwab",
  "Enjoy the little things, for one day you may look back and realize they were the big things. - Robert Brault",
  "Reflect upon your present blessings, of which every man has plenty. - Charles Dickens",
  "Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well. - Voltaire",
  "As we express our gratitude, we must never forget that the highest appreciation is not to utter words but to live by them. - John F. Kennedy",
  "Silent gratitude isn't very much to anyone. - Gertrude Stein",
  
  // Simplicity & Minimalism
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
  "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less. - Socrates",
  "Simplicity is the keynote of all true elegance. - Coco Chanel",
  "In character, in manner, in style, in all things, the supreme excellence is simplicity. - Henry Wadsworth Longfellow",
  "The ability to simplify means to eliminate the unnecessary so that the necessary may speak. - Hans Hofmann",
  "Any intelligent fool can make things bigger, more complex, and more violent. It takes genius to move in the opposite direction. - E.F. Schumacher",
  "Simplicity is not about deprivation. Simplicity is about greater clarity and purpose. - Anonymous",
  "The greatest wealth is to live content with little. - Plato",
  "Less is more. - Ludwig Mies van der Rohe",
  
  // Work & Career
  "Choose a job you love, and you will never have to work a day in your life. - Confucius",
  "Your work is going to fill a large part of your life. The only way to be truly satisfied is to do great work. - Steve Jobs",
  "Hard work beats talent when talent doesn't work hard. - Tim Notke",
  "Working hard for something we don't care about is called stress. Working hard for something we love is called passion. - Simon Sinek",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Don't be busy, be productive. - Anonymous",
  "Work to become, not to acquire. - Elbert Hubbard",
  "The price of success is hard work, dedication to the job at hand. - Vince Lombardi",
  "Pleasure in the job puts perfection in the work. - Aristotle",
  "Without labor nothing prospers. - Sophocles",
  
  // Adventure & Risk
  "Life is either a daring adventure or nothing at all. - Helen Keller",
  "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "Take risks: if you win, you will be happy; if you lose, you will be wise. - Anonymous",
  "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
  "And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom. - Anaïs Nin",
  "Do one thing every day that scares you. - Eleanor Roosevelt",
  "The person who risks nothing, does nothing, has nothing, is nothing. - Leo Buscaglia",
  "Ships in harbor are safe, but that's not what ships are built for. - John Shedd",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "Risk more than others think is safe. Dream more than others think is practical. - Howard Schultz"
];

// Export for use in content.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = QUOTES;
}